<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Payroll Records Report</title>
<style>
  *{ font-family: DejaVu Sans, sans-serif; }
  body{ font-size: 10.5px; color:#111; }
  @page { size: A4 landscape; margin: 120px 24px 60px 24px; }

  .header{ position: fixed; top: -95px; left: 0; right: 0; height: 95px; }
  .footer{ position: fixed; bottom: -45px; left: 0; right: 0; height: 45px; color:#666; font-size: 9px; }

  .hdr td{ vertical-align: top; }
  .hdr .logo{ width: 90px; }
  .hdr img{ height: 70px; display:block; }
  .h1{ font-size: 18px; font-weight: 700; margin:0; line-height:1.2; }
  .small{ font-size: 9.5px; }
  .muted{ color:#666; }
  .sep{ border:0; border-top:1px solid #ccc; margin:6px 0 0 0; }

  .report-title{ text-align:center; font-size:14px; font-weight:700; text-transform:uppercase; margin: 6px 0 10px; letter-spacing: .04em; }
  .filters{ font-size: 10px; color:#444; margin-bottom: 8px; }

  table.records{ border-collapse: collapse; width:100%; }
  table.records th, table.records td{ border:1px solid #999; padding: 5px 6px; }
  table.records th{ background:#f2f2f2; text-align:left; }
  table.records td.num{ text-align:right; }
  table.records tbody tr:nth-child(even){ background:#fafafa; }

  .totals-row td{ font-weight:700; background:#f0f0f0; }
  .pagenum:before{ content: counter(page) " / " counter(pages); }
</style>
</head>
<body>

<div class="header">
  <table class="hdr">
    <tr>
      <td class="logo">
        @if(!empty($branding['logoBase64']))
          <img src="{{ $branding['logoBase64'] }}" alt="Logo">
        @endif
      </td>
      <td>
        <div class="h1">{{ $branding['name'] ?? config('app.name', 'School') }}</div>
        <div class="small muted">
          @if(!empty($branding['address'])) {{ $branding['address'] }} |
          @endif
          @if(!empty($branding['email'])) {{ $branding['email'] }} |
          @endif
          @if(!empty($branding['phone'])) Tel: {{ $branding['phone'] }} |
          @endif
          @if(!empty($branding['website'])) {{ $branding['website'] }} @endif
        </div>
        <hr class="sep">
      </td>
      <td style="width:150px; text-align:right;">
        <div class="small muted">Date: {{ $printedAt->format('Y-m-d') }}</div>
        <div class="small muted">Time: {{ $printedAt->format('H:i') }}</div>
      </td>
    </tr>
  </table>
</div>

<div class="footer">
  <hr class="sep">
  <table>
    <tr>
      <td>Generated by: <strong>{{ $printedBy }}</strong></td>
      <td style="text-align:center;" class="muted">Printed: {{ $printedAt->format('Y-m-d H:i') }}</td>
      <td style="text-align:right;" class="muted">Page <span class="pagenum"></span></td>
    </tr>
  </table>
</div>

<div class="report-title">Payroll Records Report</div>

@if(!empty($filtersSummary))
  <div class="filters">Filters: {{ $filtersSummary }}</div>
@endif

<table class="records">
  <thead>
    <tr>
      <th>Period</th>
      <th>Staff</th>
      <th class="num">Basic Salary</th>
      <th class="num">Gross Salary</th>
      <th class="num">Deductions</th>
      <th class="num">Net Salary</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    @foreach($records as $record)
      <tr>
        <td>
          {{ $record->payrollPeriod->period_name ?? '' }}<br>
          <span class="small muted">{{ optional($record->payrollPeriod?->pay_date)->format('M d, Y') }}</span>
        </td>
        <td>
          {{ $record->staff->name ?? ('Staff #'.$record->staff_id) }}<br>
          <span class="small muted">{{ $record->staff->staff_id ?? '' }}</span>
        </td>
        <td class="num">{{ number_format((float) $record->basic_salary, 2) }}</td>
        <td class="num">{{ number_format((float) $record->gross_salary, 2) }}</td>
        <td class="num">{{ number_format((float) $record->total_deductions, 2) }}</td>
        <td class="num">{{ number_format((float) $record->net_salary, 2) }}</td>
        <td>{{ ucfirst($record->status) }}</td>
      </tr>
    @endforeach
    <tr class="totals-row">
      <td colspan="2">Totals ({{ $records->count() }} records)</td>
      <td class="num">{{ number_format($records->sum('basic_salary'), 2) }}</td>
      <td class="num">{{ number_format($records->sum('gross_salary'), 2) }}</td>
      <td class="num">{{ number_format($records->sum('total_deductions'), 2) }}</td>
      <td class="num">{{ number_format($records->sum('net_salary'), 2) }}</td>
      <td></td>
    </tr>
  </tbody>
</table>

</body>
</html>
