<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithTitle;

class ClassSheetExport implements FromArray, WithTitle
{
    public function __construct(
        private readonly array $sheetPayload,
        private readonly string $title = 'Class Sheet',
        private readonly string $generatedBy = 'System',
        private readonly ?string $schoolLine = null,
    ) {}

    public function title(): string
    {
        return mb_substr($this->title, 0, 31);
    }

    public function array(): array
    {
        $subjects = $this->sheetPayload['subjects'] ?? [];
        $rows = $this->sheetPayload['rows'] ?? [];

        $subjectNames = [];
        foreach ($subjects as $s) {
            $label = $s['code'] ? ($s['code'].' - '.$s['name']) : $s['name'];
            $subjectNames[] = $label;
        }

        $header = array_merge(
            ['#', 'Admission No', 'Student Name'],
            $subjectNames,
            ['Total', 'Average', 'Class Pos', 'Stream Pos']
        );

        $school = $this->schoolLine ?? setting('school_name', config('app.name', 'School'));
        $out = [
            [$school],
            ['Class Mark Sheet — '.$this->title],
            ['Printed '.now()->format('Y-m-d H:i').' | Generated by: '.$this->generatedBy],
            [],
            $header,
        ];

        foreach ($rows as $idx => $row) {
            $line = [
                $idx + 1,
                $row['admission_number'] ?? '',
                $row['name'] ?? '',
            ];

            foreach ($subjects as $s) {
                $sid = $s['id'];
                $line[] = $row['subject_scores'][$sid] ?? null;
            }

            $line[] = $row['total'] ?? null;
            $line[] = $row['average'] ?? null;
            $line[] = $row['class_position'] ?? $row['position'] ?? null;
            $line[] = $row['stream_position'] ?? null;
            $out[] = $line;
        }

        if (!empty($rows)) {
            $subjectAvgs = [];
            foreach ($subjects as $s) {
                $sid = $s['id'] ?? null;
                if (!$sid) {
                    $subjectAvgs[] = null;
                    continue;
                }
                $sum = 0.0;
                $count = 0;
                foreach ($rows as $r) {
                    $v = $r['subject_scores'][$sid] ?? null;
                    if ($v === null || $v === '' || !is_numeric($v)) {
                        continue;
                    }
                    $sum += (float) $v;
                    $count++;
                }
                $subjectAvgs[] = $count ? round($sum / $count, 2) : null;
            }

            $out[] = [];
            $out[] = array_merge(
                ['', '', 'Subject average'],
                $subjectAvgs,
                ['', '', '', '']
            );
        }

        return $out;
    }
}
