@php
  $reportTitle = $reportTitle ?? 'Exam Report';
  $reportSubtitle = $reportSubtitle ?? null;
  $generatedAt = isset($generatedAt) ? \Illuminate\Support\Carbon::parse($generatedAt) : now();
  $generatedBy = $generatedBy ?? (auth()->user()?->name ?? 'System');
  $variant = $variant ?? 'web-print';
  $isPdf = $variant === 'pdf';

  $schoolName = setting('school_name', config('app.name', 'School'));
  $address = trim((string) setting('school_address', ''));
  $phone = trim((string) setting('school_phone', ''));
  $email = trim((string) setting('school_email', ''));
  $website = trim((string) setting('school_website', ''));

  $logoFile = setting('school_logo');
  $logoWebUrl = $logoFile ? public_image_url($logoFile) : null;
  $logoPdfSrc = null;
  if ($isPdf && $logoFile) {
      $path = public_path('images/' . ltrim($logoFile, '/'));
      if (is_readable($path)) {
          $mime = @mime_content_type($path) ?: 'image/png';
          $logoPdfSrc = 'data:'.$mime.';base64,'.base64_encode((string) file_get_contents($path));
      }
  }
@endphp

@if($isPdf)
<table class="exam-report-letterhead-table" style="width:100%; border-collapse:collapse; margin-bottom:10px;">
  <tr>
    <td style="width:72px; vertical-align:top; padding-right:10px;">
      @if($logoPdfSrc)
        <img src="{{ $logoPdfSrc }}" alt="" style="max-height:56px; max-width:64px; display:block;">
      @endif
    </td>
    <td style="vertical-align:top;">
      <div style="font-size:14px; font-weight:700; color:#1a1a1a;">{{ $schoolName }}</div>
      <div style="font-size:8px; color:#444; line-height:1.35; margin-top:3px;">
        @if($address !== ''){{ $address }}@endif
        @if($phone !== '')<br>Tel: {{ $phone }}@endif
        @if($email !== '')<br>{{ $email }}@endif
        @if($website !== '')<br>{{ $website }}@endif
      </div>
    </td>
    <td style="width:38%; vertical-align:top; text-align:right; font-size:8px; color:#333;">
      <div style="font-size:11px; font-weight:700; margin-bottom:4px;">{{ $reportTitle }}</div>
      @if($reportSubtitle)
        <div style="font-size:8px; color:#555; margin-bottom:6px;">{{ $reportSubtitle }}</div>
      @endif
      <div>Printed: {{ $generatedAt->format('d M Y, H:i') }}</div>
      <div>Generated by: {{ $generatedBy }}</div>
    </td>
  </tr>
</table>
<div style="border-top:1px solid #333; margin:0 0 10px 0;"></div>
@else
<div class="exam-report-letterhead exam-report-letterhead--print mb-3 pb-2 border-bottom border-dark">
  <table style="width:100%; border-collapse:collapse;">
    <tr>
      <td style="width:80px; vertical-align:top;">
        @if($logoWebUrl)
          <img src="{{ $logoWebUrl }}" alt="" style="max-height:64px; max-width:72px; display:block;">
        @endif
      </td>
      <td style="vertical-align:top;">
        <div style="font-size:1.1rem; font-weight:700;">{{ $schoolName }}</div>
        <div class="small text-muted" style="line-height:1.35;">
          @if($address !== ''){{ $address }}@endif
          @if($phone !== '') &middot; Tel: {{ $phone }}@endif
          @if($email !== '') &middot; {{ $email }}@endif
          @if($website !== '') &middot; {{ $website }}@endif
        </div>
      </td>
      <td style="width:35%; vertical-align:top; text-align:right; font-size:0.8rem;">
        <div class="fw-bold">{{ $reportTitle }}</div>
        @if($reportSubtitle)
          <div class="text-muted small">{{ $reportSubtitle }}</div>
        @endif
        <div class="small mt-1">Printed: {{ $generatedAt->format('d M Y, H:i') }}</div>
        <div class="small">Generated by: {{ $generatedBy }}</div>
      </td>
    </tr>
  </table>
</div>
@endif
