<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Daily Transport List - {{ $date }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .vehicle-section {
            margin-bottom: 40px;
            page-break-inside: avoid;
        }
        .vehicle-header {
            background-color: #f0f0f0;
            padding: 10px;
            margin-bottom: 10px;
            font-weight: bold;
            font-size: 14px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #4CAF50;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 10px;
        }
        @media print {
            .vehicle-section {
                page-break-inside: avoid;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Daily Transport List</h1>
        <p><strong>Date:</strong> {{ \Carbon\Carbon::parse($date)->format('l, F j, Y') }}</p>
        <p><strong>Printed:</strong> {{ now()->format('F j, Y H:i:s') }}</p>
    </div>

    @foreach($studentsByVehicle as $vehicleNumber => $vehicleStudents)
    <div class="vehicle-section">
        <div class="vehicle-header">
            Vehicle: {{ $vehicleNumber }} - {{ $vehicleStudents->count() }} Students
        </div>
        
        <table>
            <thead>
                <tr>
                    <th style="width: 5%;">#</th>
                    <th style="width: 15%;">Admission No</th>
                    <th style="width: 30%;">Student Name</th>
                    <th style="width: 15%;">Class</th>
                    <th style="width: 15%;">Trip</th>
                    <th style="width: 20%;">Drop-off Point</th>
                </tr>
            </thead>
            <tbody>
                @foreach($vehicleStudents as $index => $student)
                @php
                    $assignment = $student->assignments->first();
                @endphp
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $student->admission_number }}</td>
                    <td>{{ $student->full_name }}</td>
                    <td>{{ $student->classroom?->name ?? 'N/A' }}</td>
                    <td>{{ $assignment?->eveningTrip?->trip_name ?? 'N/A' }}</td>
                    <td>{{ $assignment?->eveningDropOffPoint?->name ?? 'N/A' }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endforeach

    <div class="footer">
        <p>Generated by School Management System - {{ config('app.name') }}</p>
    </div>
</body>
</html>

