<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Transport List - {{ $vehicle->vehicle_number }} - {{ $date }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .vehicle-info {
            background-color: #f0f0f0;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        .vehicle-info h2 {
            margin: 0 0 10px 0;
            font-size: 18px;
        }
        .trip-section {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        .trip-header {
            background-color: #e0e0e0;
            padding: 8px;
            margin-bottom: 10px;
            font-weight: bold;
            font-size: 13px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #4CAF50;
            color: white;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .signature-section {
            margin-top: 50px;
            display: flex;
            justify-content: space-between;
        }
        .signature-box {
            width: 45%;
            border-top: 1px solid #333;
            padding-top: 10px;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #666;
            font-size: 10px;
        }
        @media print {
            .trip-section {
                page-break-inside: avoid;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Daily Transport List</h1>
        <p><strong>Date:</strong> {{ \Carbon\Carbon::parse($date)->format('l, F j, Y') }}</p>
        <p><strong>Printed:</strong> {{ now()->format('F j, Y H:i:s') }}</p>
    </div>

    <div class="vehicle-info">
        <h2>Vehicle: {{ $vehicle->vehicle_number }}</h2>
        <p><strong>Driver:</strong> {{ $vehicle->driver_name ?? 'Not Assigned' }}</p>
        <p><strong>Total Students:</strong> {{ $totalStudents }}</p>
        <p><strong>Capacity:</strong> {{ $vehicle->capacity ?? 'N/A' }}</p>
    </div>

    @foreach($studentsByTrip as $tripName => $tripStudents)
    <div class="trip-section">
        <div class="trip-header">
            {{ $tripName }} - {{ $tripStudents->count() }} Students
        </div>
        
        <table>
            <thead>
                <tr>
                    <th style="width: 5%;">#</th>
                    <th style="width: 15%;">Admission No</th>
                    <th style="width: 35%;">Student Name</th>
                    <th style="width: 15%;">Class</th>
                    <th style="width: 25%;">Drop-off Point</th>
                    <th style="width: 5%;">✓</th>
                </tr>
            </thead>
            <tbody>
                @foreach($tripStudents as $index => $student)
                @php
                    $assignment = $student->assignments->first();
                @endphp
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $student->admission_number }}</td>
                    <td>{{ $student->full_name }}</td>
                    <td>{{ $student->classroom?->name ?? 'N/A' }}</td>
                    <td>{{ $assignment?->eveningDropOffPoint?->name ?? 'N/A' }}</td>
                    <td></td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endforeach

    <div class="signature-section">
        <div class="signature-box">
            <p><strong>Driver Signature:</strong></p>
            <p>_________________________________</p>
            <p>Date: _____________________________</p>
        </div>
        <div class="signature-box">
            <p><strong>Supervisor Signature:</strong></p>
            <p>_________________________________</p>
            <p>Date: _____________________________</p>
        </div>
    </div>

    <div class="footer">
        <p>Generated by School Management System - {{ config('app.name') }}</p>
    </div>
</body>
</html>

