export type OperationsStackParamList = {
  OperationsDashboard: undefined;
  TripsList: undefined;
  TripDetail: { tripId: number; tripName?: string };
  InventoryList: undefined;
  InventoryItemDetail: { itemId: number };
  RequirementsRoster: undefined;
  RequirementsStudent: { studentId: number; studentName?: string };
  LibraryBooks: undefined;
  LibraryCirculation: undefined;
  IssueBook: undefined;
  RequisitionsList: undefined;
  RequisitionDetail: { requisitionId: number };
  RequisitionForm: undefined;
  VisitorsList: undefined;
  VisitorDetail: { visitorId: number };
  VisitorCheckIn: undefined;
  AssetsList: undefined;
  AssetDetail: { assetId: number };
  AssetForm: { assetId?: number } | undefined;
  TeacherTransport: undefined;
  DriverTrips: undefined;
  DriverTripDetail: { tripId: number; tripName?: string };
  VehiclesList: undefined;
  VehicleForm: { vehicleId?: number };
  TripForm: { tripId?: number };
};
