<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     * Increases the token column size from 20 to 64 characters to accommodate 32-character tokens
     * generated by FamilyUpdateLink::generateToken()
     */
    public function up(): void
    {
        Schema::table('family_update_links', function (Blueprint $table) {
            // Increase token column size from 20 to 64 to accommodate 32-character tokens
            DB::statement("ALTER TABLE `family_update_links` MODIFY COLUMN `token` VARCHAR(64) NOT NULL");
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('family_update_links', function (Blueprint $table) {
            // Revert token column size back to 20
            DB::statement("ALTER TABLE `family_update_links` MODIFY COLUMN `token` VARCHAR(20) NOT NULL");
        });
    }
};
