<?php

return [
    'nationalities' => [
        'Kenyan',
        'Ugandan',
        'Tanzanian',
        'Rwandan',
        'Burundian',
        'South Sudanese',
        'Ethiopian',
        'Somali',
        'Other',
    ],

    'counties' => [
        'Mombasa',
        'Kwale',
        'Kilifi',
        'Tana River',
        'Lamu',
        'Taita-Taveta',
        'Garissa',
        'Wajir',
        'Mandera',
        'Marsabit',
        'Isiolo',
        'Meru',
        'Tharaka-Nithi',
        'Embu',
        'Kitui',
        'Machakos',
        'Makueni',
        'Nyandarua',
        'Nyeri',
        'Kirinyaga',
        "Murang'a",
        'Kiambu',
        'Turkana',
        'West Pokot',
        'Samburu',
        'Trans Nzoia',
        'Uasin Gishu',
        'Elgeyo-Marakwet',
        'Nandi',
        'Baringo',
        'Laikipia',
        'Nakuru',
        'Narok',
        'Kajiado',
        'Kericho',
        'Bomet',
        'Kakamega',
        'Vihiga',
        'Bungoma',
        'Busia',
        'Siaya',
        'Kisumu',
        'Homa Bay',
        'Migori',
        'Kisii',
        'Nyamira',
        'Nairobi',
    ],

    'religions' => [
        'Christian',
        'Muslim',
        'Hindu',
        'Traditional',
        'Other',
    ],

    'learner_interests' => [
        'Music',
        'Sports',
        'Environmental',
        'Science',
        'Drama',
        'Art',
    ],

    'orphan_statuses' => [
        'none' => 'Not an orphan',
        'maternal' => 'Maternal orphan',
        'paternal' => 'Paternal orphan',
        'total' => 'Total orphan',
    ],

    'disability_types' => [
        'Visual',
        'Hearing',
        'Physical',
        'Mental',
        'Speech',
        'Autism',
        'Multiple',
        'Other',
    ],

    'id_types' => [
        'National ID',
        'Passport',
        'Alien ID',
        'Military ID',
        'Other',
    ],

    'countries_of_residence' => [
        'Kenya',
        'Uganda',
        'Tanzania',
        'Rwanda',
        'Burundi',
        'South Sudan',
        'Ethiopia',
        'Somalia',
        'United Kingdom',
        'United States',
        'United Arab Emirates',
        'Saudi Arabia',
        'Other',
    ],
];
