<?php

/**
 * Navigation visibility by role — aligned with route middleware in routes/web.php.
 * Super Admin and Director always see every section (handled in NavAccess).
 */
return [
    'role_order' => [
        'Super Admin',
        'Director',
        'Admin',
        'Secretary',
        'Academic Administrator',
        'Finance Officer',
        'Accountant',
        'Senior Teacher',
        'Deputy Senior Teacher',
        'Supervisor',
        'Teacher',
        'Driver',
        'Parent',
        'Student',
    ],

    'module_labels' => [
        'admin' => 'Admin / Dashboard',
        'teacher' => 'Teacher',
        'student' => 'Student',
        'transport' => 'Transport',
        'students' => 'Students',
        'staff' => 'Staff / HR',
        'attendance' => 'Attendance',
        'communication' => 'Communication',
        'settings' => 'Settings',
        'admissions' => 'Admissions',
        'finance' => 'Finance',
        'academics' => 'Academics',
        'subjects' => 'Subjects',
        'classrooms' => 'Classrooms',
        'learning_areas' => 'Learning Areas',
        'cbc_strands' => 'CBC Strands',
        'cbc_substrands' => 'CBC Substrands',
        'competencies' => 'Competencies',
        'schemes_of_work' => 'Schemes of Work',
        'lesson_plans' => 'Lesson Plans',
        'portfolio_assessments' => 'Portfolio Assessments',
        'exams' => 'Exams',
        'exam_types' => 'Exam Types',
        'exam_marks' => 'Exam Marks',
        'report_cards' => 'Report Cards',
        'report_card_skills' => 'Report Card Skills',
        'homework' => 'Homework',
        'diaries' => 'Digital Diaries',
        'student_behaviours' => 'Student Behaviour',
        'timetable' => 'Timetable',
        'curriculum_designs' => 'Curriculum Designs',
        'curriculum_assistant' => 'Curriculum Assistant',
        'exports' => 'Exports',
        'audit_logs' => 'Audit Logs',
        'expense' => 'Expenses',
        'voucher' => 'Payment Vouchers',
        'vendor' => 'Vendors',
        'dashboard' => 'Dashboards',
        'inventory' => 'Inventory',
        'events' => 'Events',
        'manage' => 'Legacy / Manage',
        'senior_teacher' => 'Senior Teacher',
        'extra_curricular' => 'Extra Curricular',
        'website_cms' => 'Website CMS',
        'pos' => 'Point of Sale',
        'documents' => 'Documents',
        'campus_reports' => 'Campus & Weekly Reports',
        'school_operations' => 'School Operations',
        'payroll' => 'Payroll',
        'cbc' => 'CBC Curriculum',
        'assessments' => 'Assessments',
        'behaviours' => 'Behaviours',
        'hr' => 'HR / Staff',
        'gallery' => 'Gallery',
        'profile' => 'My Profile',
    ],

    'dashboards' => [
        'admin.dashboard' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Academic Administrator'],
        'teacher.dashboard' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Teacher', 'teacher', 'Supervisor'],
        'senior_teacher.dashboard' => ['Senior Teacher', 'Deputy Senior Teacher'],
        'student.dashboard' => ['Student'],
        'parent.dashboard' => ['Parent'],
        'finance.dashboard' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Accountant', 'Finance Officer'],
        'transport.dashboard' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Driver'],
        'supervisor.dashboard' => ['Supervisor'],
        'gallery.index' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Teacher', 'teacher', 'Senior Teacher', 'Deputy Senior Teacher', 'Supervisor', 'Accountant', 'Finance Officer', 'Academic Administrator'],
    ],

    'sections' => [
        'gallery' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Teacher', 'teacher', 'Senior Teacher', 'Deputy Senior Teacher', 'Supervisor', 'Accountant', 'Finance Officer', 'Academic Administrator'],
        'profile' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Academic Administrator', 'Finance Officer', 'Accountant', 'Senior Teacher', 'Deputy Senior Teacher', 'Supervisor', 'Teacher', 'teacher', 'Driver', 'Parent', 'Student'],
        'students' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Academic Administrator'],
        'attendance' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Academic Administrator'],
        'academics' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Academic Administrator'],
        'cbc' => ['Super Admin', 'Director', 'Admin', 'Secretary'],
        'timetable' => ['Super Admin', 'Director', 'Admin', 'Secretary'],
        'homework' => ['Super Admin', 'Director', 'Admin', 'Secretary'],
        'exams' => ['Super Admin', 'Director', 'Admin', 'Secretary'],
        'report_cards' => ['Super Admin', 'Director', 'Admin', 'Secretary'],
        'assessments' => ['Super Admin', 'Director', 'Admin', 'Secretary'],
        'campus_reports' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Senior Teacher', 'Deputy Senior Teacher'],
        'behaviours' => ['Super Admin', 'Director', 'Admin', 'Secretary'],
        'finance' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Accountant', 'Finance Officer'],
        'transport' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Driver', 'Senior Teacher', 'Deputy Senior Teacher'],
        'communication' => ['Super Admin', 'Director', 'Admin', 'Secretary'],
        'hr' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Senior Teacher', 'Deputy Senior Teacher'],
        'payroll' => ['Super Admin', 'Director', 'Secretary'],
        'events' => ['Super Admin', 'Director', 'Admin', 'Secretary', 'Teacher', 'teacher', 'Senior Teacher', 'Deputy Senior Teacher', 'Supervisor'],
        'inventory' => ['Super Admin', 'Director', 'Admin', 'Secretary'],
        'pos' => ['Super Admin', 'Director', 'Admin', 'Secretary'],
        'documents' => ['Super Admin', 'Director', 'Admin', 'Secretary'],
        'settings' => ['Super Admin', 'Director', 'Admin', 'Secretary'],
        'website_cms' => ['Super Admin', 'Director', 'Admin', 'Secretary'],
        'school_operations' => ['Super Admin', 'Director', 'Admin', 'Secretary'],
    ],

    /**
     * Every module and submodule shown on Roles & Lookups.
     * Each row gets view, create, edit, and delete. Extra actions already
     * stored on that key stay under More.
     */
    'permission_catalog' => [
        ['label' => 'Students', 'rows' => [
            ['key' => 'students', 'label' => 'Student records'],
            ['key' => 'admissions', 'label' => 'Admissions'],
        ]],
        ['label' => 'Attendance', 'rows' => [
            ['key' => 'attendance', 'label' => 'Attendance'],
        ]],
        ['label' => 'Academics', 'rows' => [
            ['key' => 'academics', 'label' => 'Academics'],
            ['key' => 'classrooms', 'label' => 'Classrooms'],
            ['key' => 'subjects', 'label' => 'Subjects'],
            ['key' => 'learning_areas', 'label' => 'Learning areas'],
            ['key' => 'extra_curricular', 'label' => 'Clubs and activities'],
            ['key' => 'timetable', 'label' => 'Timetable'],
        ]],
        ['label' => 'CBC and curriculum', 'rows' => [
            ['key' => 'cbc', 'label' => 'CBC'],
            ['key' => 'cbc_strands', 'label' => 'Strands'],
            ['key' => 'cbc_substrands', 'label' => 'Substrands'],
            ['key' => 'competencies', 'label' => 'Competencies'],
            ['key' => 'schemes_of_work', 'label' => 'Schemes of work'],
            ['key' => 'lesson_plans', 'label' => 'Lesson plans'],
            ['key' => 'curriculum_designs', 'label' => 'Curriculum designs'],
            ['key' => 'portfolio_assessments', 'label' => 'Portfolio assessments'],
        ]],
        ['label' => 'Homework and diaries', 'rows' => [
            ['key' => 'homework', 'label' => 'Homework'],
            ['key' => 'diaries', 'label' => 'Digital diaries'],
        ]],
        ['label' => 'Exams and reports', 'rows' => [
            ['key' => 'exams', 'label' => 'Exams'],
            ['key' => 'exam_types', 'label' => 'Exam types'],
            ['key' => 'exam_marks', 'label' => 'Exam marks'],
            ['key' => 'assessments', 'label' => 'Assessments'],
            ['key' => 'report_cards', 'label' => 'Report cards'],
            ['key' => 'student_behaviours', 'label' => 'Behaviour'],
        ]],
        ['label' => 'Finance', 'rows' => [
            ['key' => 'finance', 'label' => 'Finance'],
            ['key' => 'expense', 'label' => 'Expenses'],
            ['key' => 'voucher', 'label' => 'Payment vouchers'],
            ['key' => 'vendor', 'label' => 'Vendors'],
            ['key' => 'pos', 'label' => 'Point of sale'],
        ]],
        ['label' => 'Transport', 'rows' => [
            ['key' => 'transport', 'label' => 'Transport'],
        ]],
        ['label' => 'Communication', 'rows' => [
            ['key' => 'communication', 'label' => 'Communication'],
        ]],
        ['label' => 'Staff', 'rows' => [
            ['key' => 'staff', 'label' => 'Staff records'],
            ['key' => 'hr', 'label' => 'Leave, attendance and documents'],
            ['key' => 'documents', 'label' => 'Documents'],
        ]],
        ['label' => 'Payroll', 'rows' => [
            ['key' => 'payroll', 'label' => 'Payroll and salaries'],
        ]],
        ['label' => 'Operations', 'rows' => [
            ['key' => 'inventory', 'label' => 'Inventory'],
            ['key' => 'school_operations', 'label' => 'School operations'],
            ['key' => 'events', 'label' => 'Events'],
            ['key' => 'gallery', 'label' => 'Gallery'],
            ['key' => 'campus_reports', 'label' => 'Campus reports'],
            ['key' => 'website_cms', 'label' => 'Website'],
        ]],
        ['label' => 'Settings', 'rows' => [
            ['key' => 'settings', 'label' => 'Settings and roles'],
            ['key' => 'audit_logs', 'label' => 'Audit logs'],
            ['key' => 'dashboard', 'label' => 'Dashboards'],
        ]],
    ],
];
