export type ParentStackParamList = {
  ParentHome: undefined;
  ChildrenList: undefined;
  ChildHub: { studentId: number };
  ChildProfile: { studentId: number };
  ChildResults: { studentId: number };
  ReportCardDetail: { studentId: number; reportCardId: number };
  ChildAttendance: { studentId: number };
  ChildHomework: { studentId: number };
  FeesHome: undefined;
  AcademicHome: undefined;
  InvoiceDetail: { studentId: number; invoiceId: number };
  PaymentDetail: { studentId: number; paymentId: number };
  WalletHome: { payInvoiceId?: number; studentId?: number } | undefined;
  WalletTopUp: undefined;
  WalletSavingPlans: undefined;
  WalletSavingPlanForm: { planId?: number } | undefined;
  StudentDetail: { studentId: number };
  StudentStatement: { studentId: number };
  MpesaPrompt: { studentId: number; amount?: number };
  DiaryList: undefined;
  DiaryChat: { studentId: number };
  Announcements: undefined;
  Notifications: undefined;
  Settings: undefined;
  MoreMenu: undefined;
  MyProfile: undefined;
  ConcernsList: undefined;
  Transport: { studentId: number };
  LiveBusTrack: { studentId: number };
  RaiseConcern: { studentId?: number };
};
