export type TeacherStackParamList = {
  Main: undefined;
  MarkAttendance: undefined;
  MarksHub: undefined;
  MarksMatrixSetup: undefined;
  MarksMatrixEntry: { examTypeId: number; classroomId: number; streamId?: number };
  MarksExamSetup: { examId: number; examName: string };
  MarksEntry: {
    examId: number;
    classroomId: number;
    subjectId: number;
    classroomName: string;
    subjectName: string;
  };
  LessonPlansHub: undefined;
  LessonPlanDetail: { lessonPlanId: number; topic?: string };
  CreateLessonPlan: undefined;
  TimetableHub: undefined;
  RequirementsHub: undefined;
  RequirementDetail: { studentId: number };
  StaffClock: undefined;
  LeaveApply: undefined;
  MyLeaveList: undefined;
  MyPayslips: undefined;
  MyProfile: undefined;
  TeacherTransportHub: undefined;
  LessonPlanReview: undefined;
  LessonPlanReviewDetail: { lessonPlanId: number; topic?: string };
  DiaryList: undefined;
  DiaryChat: { studentId: number; studentName?: string };
  Announcements: undefined;
  Notifications: undefined;
  Settings: undefined;
  StudentDetail: { studentId: number };
  AssignmentsHub: undefined;
  CreateAssignment: undefined;
  AssignmentDetail: { assignmentId: number };
  MyAdvances: undefined;
  ConcernsList: undefined;
  RaiseConcern: { studentId?: number } | undefined;
};
