@php
  $school = $branding ?? [];
  $logo   = $school['logoBase64'] ?? null;
  $invoiceBundles = $invoiceBundles ?? [];
@endphp
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Invoices (Bulk PDF)</title>
<style>
  *{ font-family: DejaVu Sans, sans-serif; }
  body{
    font-size: 10.5px;
    color:#111;
    position: relative;
  }
  @page {
    size: A4 portrait;
    margin: 135px 22px 78px 22px;
  }

  .watermark {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 350px;
    height: 350px;
    min-width: 350px;
    min-height: 350px;
    background-size: contain;
    background-repeat: no-repeat;
    background-position: center center;
    opacity: 0.15;
    z-index: 0;
    pointer-events: none;
  }

  .header{ position: fixed; top: -105px; left: 0; right: 0; height: 105px; }
  .footer{ position: fixed; bottom: -60px; left: 0; right: 0; height: 58px; color:#666; font-size: 9.5px; }

  .h1{ font-size: 18px; font-weight: 700; margin:0; line-height:1.2; }
  .small{ font-size: 9.5px; }
  .muted{ color:#666; }
  .sep{ border:0; border-top:1px solid #ccc; margin:6px 0 0 0; }

  table{ border-collapse: collapse; width:100%; }
  .hdr td{ vertical-align: top; }
  .hdr .logo { width: 100px; }
  .hdr img { height: 72px; display:block; }

  .kv{ margin-top: 6px; table-layout: fixed; }
  .kv th, .kv td{ border:1px solid #bbb; padding:5px 7px; }
  .kv th{ background:#f5f5f5; width:18%; text-align:left; }
  .kv td{ width:32%; word-wrap: break-word; }

  .class-banner{
    background:#eceaf4;
    border:1px solid #c4bdd4;
    padding:6px 10px;
    font-weight:700;
    font-size:11px;
    margin: 0 0 8px 0;
    color:#333;
  }

  .invoice-page{
    page-break-inside: avoid;
  }

  .items{ margin-top: 6px; font-size: 9.5px; }
  .items th, .items td{ border:1px solid #999; padding:5px 5px; }
  .items th{ background:#f2f2f2; font-size:9px; }
  .right{ text-align:right; }
  .center{ text-align:center; }

  .summary{
    margin-top:8px;
    border:1px solid #333;
    padding:8px 10px;
    background:#fafafa;
  }
  .summary table{ width:100%; }
  .summary td{ padding:3px 0; }
  .summary .label{ font-weight:700; width:55%; }
  .summary .amt{ text-align:right; font-weight:700; }

  .paytbl{ margin-top:6px; font-size:9.5px; }
  .paytbl th, .paytbl td{ border:1px solid #999; padding:5px 6px; }
  .paytbl th{ background:#e8f4e8; }

  .inv-title{ font-size:12px; font-weight:700; margin:4px 0 6px 0; color:#222; }

  .pagenum:before{ content: counter(page) " / " counter(pages); }

  .note-internal{ font-size:8.5px; color:#555; font-style:italic; }
</style>
</head>
<body>

@php
  $watermarkLogo = $school['logoBase64'] ?? $branding['logoBase64'] ?? null;
@endphp
@if($watermarkLogo)
<div class="watermark" style="background-image: url('{!! $watermarkLogo !!}');"></div>
@endif

{{-- Fixed header on every page --}}
<div class="header">
  <table class="hdr">
    <tr>
      <td class="logo">
        @if($logo)
          <img src="{{ $logo }}" alt="Logo">
        @endif
      </td>
      <td>
        <div class="h1">{{ $school['name'] ?? config('app.name','Your School') }}</div>
        <div class="small muted">
          @if(!empty($school['address'])) {{ $school['address'] }} |
          @endif
          @if(!empty($school['email'])) {{ $school['email'] }} |
          @endif
          @if(!empty($school['phone'])) Tel: {{ $school['phone'] }} |
          @endif
          @if(!empty($school['website'])) {{ $school['website'] }} @endif
        </div>
        @if(!empty($invoiceHeader ?? ''))
          <div class="small muted">{!! $invoiceHeader !!}</div>
        @endif
        <div class="small muted">
          Export filters:
          @foreach(['year'=>'Year','term'=>'Term','votehead_id'=>'Votehead','class_id'=>'Class','stream_id'=>'Stream','student_id'=>'Student','status'=>'Status'] as $k=>$l)
            @if(!empty($filters[$k])) {{ $l }}={{ $filters[$k] }}; @endif
          @endforeach
          Sorted by class, stream, first name.
        </div>
        <hr class="sep">
      </td>
      <td style="width:160px; text-align:right;">
        <div class="small muted">Run: {{ ($printedAt ?? now())->format('Y-m-d H:i') }}</div>
      </td>
    </tr>
  </table>
</div>

{{-- Fixed footer on every page --}}
<div class="footer">
  <hr class="sep">
  <table>
    <tr>
      <td>Generated by: <strong>{{ $printedBy ?? 'System' }}</strong></td>
      <td class="center muted">A4 · one invoice per page</td>
      <td class="right muted">Page <span class="pagenum"></span></td>
    </tr>
  </table>
</div>

@php $lastClassId = null; @endphp
@foreach($invoiceBundles as $bundle)
  @php
    $invoice = $bundle['invoice'];
    $payment_rows = $bundle['payment_rows'] ?? [];
    $s = $invoice->student;
    $classId = $s->classroom_id ?? null;
  @endphp
  <div class="invoice-page" @if(!$loop->last) style="page-break-after: always;" @endif>
    @if($classId !== $lastClassId)
      @php $lastClassId = $classId; @endphp
      <div class="class-banner">Class: {{ $s->classroom->name ?? '—' }}</div>
    @endif

    <div class="inv-title">Fee invoice</div>

    <table class="kv">
      <tr>
        <th>Student name</th>
        <td>{{ $s->full_name ?? 'Unknown' }}</td>
        <th>Admission #</th>
        <td>{{ $s->admission_number ?? '-' }}</td>
      </tr>
      <tr>
        <th>Class</th>
        <td>{{ $s->classroom->name ?? '-' }}</td>
        <th>Stream</th>
        <td>{{ $s->stream->name ?? '-' }}</td>
      </tr>
      <tr>
        <th>Invoice #</th>
        <td>{{ $invoice->invoice_number }}</td>
        <th>Period</th>
        <td>{{ $invoice->year }} / Term {{ $invoice->term }}</td>
      </tr>
      <tr>
        <th>Status</th>
        <td colspan="3">{{ strtoupper($invoice->status ?? '—') }}</td>
      </tr>
    </table>

    <table class="items">
      <thead>
        <tr>
          <th style="width:4%">#</th>
          <th>Votehead</th>
          <th style="width:12%" class="right">Charged</th>
          <th style="width:10%" class="right">Discount</th>
          <th style="width:12%" class="right">Paid (allocated)</th>
          <th style="width:12%" class="right">Balance (line)</th>
        </tr>
      </thead>
      <tbody>
        @php
          $activeItems = $invoice->items->filter(fn($item) => ($item->status ?? 'active') === 'active');
          $sumPaidLines = 0; $sumDue = 0;
        @endphp
        @foreach($activeItems as $i => $item)
          @php
            $disc = (float) ($item->discount_amount ?? 0);
            $net = (float) $item->amount - $disc;
            $paidLine = $item->allocations->filter(fn($a) => $a->payment && !$a->payment->reversed)->sum('amount');
            $dueLine = max(0, round($net - (float) $paidLine, 2));
            $sumNet += $net;
            $sumPaidLines += (float) $paidLine;
            $sumDue += $dueLine;
          @endphp
          <tr>
            <td class="center">{{ $i + 1 }}</td>
            <td>{{ $item->votehead->name ?? '—' }}</td>
            <td class="right">{{ number_format($item->amount, 2) }}</td>
            <td class="right">{{ $disc > 0 ? number_format($disc, 2) : '—' }}</td>
            <td class="right">{{ number_format($paidLine, 2) }}</td>
            <td class="right">{{ number_format($dueLine, 2) }}</td>
          </tr>
        @endforeach
        <tr>
          <th colspan="2" class="right">Totals (lines)</th>
          <th class="right">{{ number_format($activeItems->sum(fn($it) => (float)$it->amount), 2) }}</th>
          <th class="right">{{ number_format($activeItems->sum(fn($it) => (float)($it->discount_amount ?? 0)), 2) }}</th>
          <th class="right">{{ number_format($sumPaidLines, 2) }}</th>
          <th class="right">{{ number_format($sumDue, 2) }}</th>
        </tr>
      </tbody>
    </table>

    <div class="summary">
      <table>
        <tr>
          <td class="label">Invoice total (after discounts)</td>
          <td class="amt">KES {{ number_format((float) $invoice->total, 2) }}</td>
        </tr>
        <tr>
          <td class="label">Total payments allocated to this invoice</td>
          <td class="amt">KES {{ number_format((float) $invoice->paid_amount, 2) }}</td>
        </tr>
        <tr>
          <td class="label">Current balance due</td>
          <td class="amt" style="color:{{ ($invoice->balance ?? 0) > 0 ? '#b00020' : '#1b5e20' }};">KES {{ number_format((float) $invoice->balance, 2) }}</td>
        </tr>
      </table>
    </div>

    <div style="margin-top:8px;">
      <strong style="font-size:10px;">Payments applied to this invoice</strong>
      @if(count($payment_rows) > 0)
        <table class="paytbl">
          <thead>
            <tr>
              <th>Date</th>
              <th>Receipt</th>
              <th>Method</th>
              <th class="right">Amount (this invoice)</th>
            </tr>
          </thead>
          <tbody>
            @foreach($payment_rows as $pr)
              <tr>
                <td>{{ $pr['date'] ? \Carbon\Carbon::parse($pr['date'])->format('Y-m-d') : '—' }}</td>
                <td>{{ $pr['receipt'] }}</td>
                <td>{{ $pr['method'] }}@if(!empty($pr['is_internal'])) <span class="note-internal">(balance transfer)</span>@endif</td>
                <td class="right">{{ number_format($pr['amount'], 2) }}</td>
              </tr>
            @endforeach
          </tbody>
        </table>
      @else
        <p class="small muted" style="margin:4px 0;">No payments have been allocated to this invoice yet.</p>
      @endif
    </div>

    @if(!empty($invoiceFooterTemplate ?? ''))
      <div class="muted" style="margin-top:10px; font-size:9px;">{!! \App\Services\InvoiceFooterPlaceholderService::replace($invoiceFooterTemplate, $invoice) !!}</div>
    @endif
  </div>
@endforeach

</body>
</html>
