@php
  $school = $branding ?? [];
  $logo   = $school['logoBase64'] ?? null;
  $s      = $invoice->student;
@endphp
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Invoice {{ $invoice->invoice_number }}</title>
<style>
  *{ font-family: DejaVu Sans, sans-serif; }
  body{ 
    font-size: 11.5px; 
    color:#111;
    position: relative;
  }
  @page { 
    size: A4;
    margin: 135px 24px 80px 24px; /* top, right, bottom, left */
  }
  
  .watermark {
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 400px;
    height: 400px;
    background-size: contain;
    background-repeat: no-repeat;
    background-position: center;
    opacity: 0.08;
    z-index: -1;
    pointer-events: none;
  }

  /* Fixed header/footer for DomPDF */
  .header{ position: fixed; top: -105px; left: 0; right: 0; height: 105px; }
  .footer{ position: fixed; bottom: -62px; left: 0; right: 0; height: 62px; color:#666; font-size: 10px; }

  .small{ font-size: 10.5px; }
  .muted{ color:#666; }
  .h1{ font-size: 20px; font-weight: 700; margin:0; line-height:1.2; }

  .sep{ border:0; border-top:1px solid #ccc; margin:6px 0 0 0; }

  table{ border-collapse: collapse; width:100%; }
  .hdr td{ vertical-align: top; }
  .hdr .logo { width: 82px; }
  .hdr img { height: 64px; display:block; }

  .kv{ margin-top: 6px; table-layout: fixed; }
  .kv th,
  .kv td { padding: 6px 8px; border:1px solid #bbb; }
  .kv th { width: 22%; background:#f5f5f5; text-align:left; white-space:nowrap; }
  .kv td { width: 28%; word-wrap: break-word; }

  .items{ margin-top: 10px; }
  .items th,
  .items td { padding: 7px 8px; border:1px solid #999; }
  .items th{ background:#f2f2f2; }
  .right{ text-align: right; }
  .center{ text-align: center; }

  .badge{ padding: 2px 6px; border-radius: 3px; font-size: 10.5px; display:inline-block; }
  .b-active{ background:#c8e6c9; }
  .b-pending{ background:#ffe082; }

  .pagenum:before{ content: counter(page) " / " counter(pages); }
</style>
</head>
<body>

@if($logo)
<div class="watermark" style="background-image: url('{{ $logo }}');"></div>
@endif

{{-- ============ HEADER ============ --}}
<div class="header">
  <table class="hdr">
    <tr>
      <td class="logo">
        @if($logo)
          <img src="{{ $logo }}" alt="Logo">
        @endif
      </td>
      <td>
        <div class="h1">{{ $school['name'] ?? config('app.name','Your School') }}</div>
        <div class="small muted">
          @if(!empty($school['address'])) {{ $school['address'] }} |
          @endif
          @if(!empty($school['email'])) {{ $school['email'] }} |
          @endif
          @if(!empty($school['phone'])) Tel: {{ $school['phone'] }} |
          @endif
          @if(!empty($school['website'])) {{ $school['website'] }} @endif
        </div>
        @if(!empty($invoiceHeader ?? ''))
          <div class="small muted">{!! $invoiceHeader !!}</div>
        @endif
        <hr class="sep">
      </td>
      <td style="width:170px; text-align:right;">
        <div class="small muted">Date: {{ ($printedAt ?? now())->format('Y-m-d') }}</div>
        <div class="small muted">Time: {{ ($printedAt ?? now())->format('H:i') }}</div>
        <div class="small"><strong>Invoice #:</strong> {{ $invoice->invoice_number }}</div>
      </td>
    </tr>
  </table>
</div>

{{-- ============ FOOTER ============ --}}
<div class="footer">
  <hr class="sep">
  <table>
    <tr>
      <td>Generated by: <strong>{{ $printedBy ?? 'System' }}</strong></td>
      <td class="center muted">Printed: {{ ($printedAt ?? now())->format('Y-m-d H:i') }}</td>
      <td class="right muted">Page <span class="pagenum"></span></td>
    </tr>
  </table>
  @if(!empty($invoiceFooter ?? ''))
    <div class="muted" style="margin-top:4px;">{!! $invoiceFooter !!}</div>
  @endif
</div>

{{-- ============ BODY ============ --}}
<table class="kv">
  <tr>
    <th>Student</th>
    <td>{{ $s->full_name ?? 'Unknown' }} (Adm: {{ $s->admission_number ?? '-' }})</td>
    <th>Class / Stream</th>
    <td>{{ $s->classroom->name ?? '-' }} / {{ $s->stream->name ?? '-' }}</td>
  </tr>
  <tr>
    <th>Period</th>
    <td>{{ $invoice->year }} / Term {{ $invoice->term }}</td>
    <th></th>
    <td></td>
  </tr>
</table>

<table class="items">
  <thead>
    <tr>
      <th style="width:6%">#</th>
      <th>Votehead</th>
      <th style="width:16%">Status</th>
      <th style="width:18%">Effective</th>
      <th style="width:16%" class="right">Amount</th>
    </tr>
  </thead>
  <tbody>
    @php 
      // Only show active items (pending items are excluded)
      $activeItems = $invoice->items->filter(function($item) {
          return ($item->status ?? 'active') === 'active';
      });
      $total=0; 
    @endphp
    @foreach($activeItems as $i=>$item)
      @php $total+=$item->amount; $ed=$item->effective_date; @endphp
      <tr>
        <td class="center">{{ $i+1 }}</td>
        <td>{{ $item->votehead->name ?? 'Unknown' }}</td>
        <td>
          @if(($item->status ?? 'active')==='active')
            <span class="badge b-active">Active</span>
          @else
            <span class="badge b-pending">Pending</span>
          @endif
        </td>
        <td>{{ $ed ? (method_exists($ed,'format') ? $ed->format('Y-m-d') : $ed) : '-' }}</td>
        <td class="right">{{ number_format($item->amount,2) }}</td>
      </tr>
    @endforeach
    <tr>
      <th colspan="4" class="right">Total</th>
      <th class="right">{{ number_format($total,2) }}</th>
    </tr>
  </tbody>
</table>

</body>
</html>
