<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Fee Clearance Status - {{ $term?->name ?? 'Term' }}</title>
    <style>
        @page { margin: 18px 18px 60px 18px; }
        body { font-family: Arial, sans-serif; font-size: 11px; color: #111827; }
        .page { page-break-before: always; }
        .page:first-of-type { page-break-before: auto; }

        .group-title {
            background: #111827;
            color: #ffffff;
            padding: 8px 10px;
            font-weight: 700;
            font-size: 12px;
            margin: 0 0 10px 0;
        }

        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #e5e7eb; padding: 6px 8px; vertical-align: top; }
        th { background: #f3f4f6; font-size: 10px; text-transform: uppercase; letter-spacing: 0.02em; }
        tbody tr:nth-child(even) { background: #fafafa; }

        .status {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 10px;
            font-size: 10px;
            font-weight: 700;
        }
        .status--cleared { background: #dcfce7; color: #166534; }
        .status--pending { background: #fee2e2; color: #991b1b; }

        .footer {
            position: fixed;
            bottom: -45px;
            left: 0;
            right: 0;
            height: 45px;
            border-top: 1px solid #e5e7eb;
            padding-top: 8px;
            font-size: 9px;
            color: #6b7280;
        }
        .footer .row { width: 100%; }
        .footer .left { float: left; }
        .footer .right { float: right; }
    </style>
</head>
<body>
    @php
        $reportTitle = 'Financial Status (Fee Clearance) — By Class/Stream';
        $reportSubtitle = $term
            ? ($term->name . ($term->academicYear ? ' (' . $term->academicYear->year . ')' : ''))
            : null;
        $generatedAt = now();
        $generatedBy = $generated_by ?? (auth()->user()?->name ?? 'System');
    @endphp

    @foreach($groups as $classStream => $students)
        <div class="page">
            @include('academics.exam_reports.partials.report_letterhead', [
                'variant' => 'pdf',
                'reportTitle' => $reportTitle,
                'reportSubtitle' => $reportSubtitle,
                'generatedAt' => $generatedAt,
                'generatedBy' => $generatedBy,
            ])

            <div class="group-title">
                {{ str_replace(' | ', ' — ', $classStream) }} ({{ $students->count() }})
            </div>

            <table>
                <thead>
                    <tr>
                        <th style="width: 6%;">#</th>
                        <th style="width: 54%;">Student Name</th>
                        <th style="width: 18%;">Admission No</th>
                        <th style="width: 22%;">Fee Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($students as $i => $st)
                        <tr>
                            <td>{{ $i + 1 }}</td>
                            <td>{{ $st['full_name'] }}</td>
                            <td>{{ $st['admission_number'] }}</td>
                            <td>
                                @if(($st['status'] ?? 'pending') === 'cleared')
                                    <span class="status status--cleared">Cleared</span>
                                @else
                                    <span class="status status--pending">Pending</span>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    @endforeach

    <div class="footer">
        <div class="left">Report generated by: {{ $generatedBy }}</div>
        <div class="right">Date: {{ ($generated_at ?? now()->format('Y-m-d H:i')) }}</div>
    </div>
</body>
</html>

